services:
  - type: web
    name: mega-telegram-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token-here
